spring.datasource.url=jdbc:postgresql://messaging-db:5432/messaging_db
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=messaging_user
spring.datasource.password=messaging_pass
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.hostname=messaging-service
eureka.instance.prefer-ip-address=false
