spring.datasource.url=jdbc:postgresql://meal-db:5432/meal_db
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=meal_user
spring.datasource.password=meal_pass
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.hostname=meal-service
eureka.instance.prefer-ip-address=false
