spring.datasource.url=jdbc:postgresql://school-db:5432/school_db
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=school_user
spring.datasource.password=school_pass
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.hostname=school-service
eureka.instance.prefer-ip-address=false
